export enum Permission {
  MANAGE_EXPENSES = 'MANAGE_EXPENSES',
  MANAGE_SANCTIONS = 'MANAGE_SANCTIONS',
  MANAGE_MEMBERS = 'MANAGE_MEMBERS',
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  MANAGE_SESSIONS = 'MANAGE_SESSIONS',
  MANAGE_SAVINGS = 'MANAGE_SAVINGS',
  MANAGE_TONTINES = 'MANAGE_TONTINES',
  MANAGE_SMALL_TONTINE = 'MANAGE_SMALL_TONTINE',
  MANAGE_LOANS = 'MANAGE_LOANS',
  MANAGE_AIDS = 'MANAGE_AIDS'
}
